services:
  redis-cache:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: on-failure:5

  react-app:
    build: ./client
    restart: on-failure:5

  node-api:
    build: ./server
    environment:
      SPOTIFY_CLIENT_ID: MY_CLIENT_ID
      SPOTIFY_CLIENT_SECRET: MY_CLIENT_SECRET
      COOKIE_SIGNER: MY_COOKIE_SIGNER
      JWT_SECRET: MY_JWT_SECRET
      TTL: 86400
    depends_on:
      - redis-cache
    restart: on-failure:5
    volumes:
      - node-data:/var/log/node

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - node-api
      - react-app
    restart: on-failure:5
    volumes:
      - nginx-data:/var/log/nginx

  post-start:
    image: redis/redis-stack-server:latest
    depends_on:
      - redis-cache
    command: ["sh", "-c", "redis-cli -h redis-cache CONFIG SET save '60 1'"]

  redis-exporter:
    image: oliver006/redis_exporter
    environment:
      REDIS_ADDR: "redis-cache:6379"
    depends_on:
      - redis-cache
    restart: on-failure:5

  nginx-react-exporter:
    image: nginx/nginx-prometheus-exporter
    command: -nginx.scrape-uri=http://react-app:8080/stub_status
    depends_on:
      - react-app
    restart: on-failure:5

  node-prometheus-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($|/)"'
    restart: on-failure:5

  nginx-main-exporter:
    image: nginx/nginx-prometheus-exporter
    command: -nginx.scrape-uri=http://nginx:8080/stub_status
    depends_on:
      - nginx
    restart: on-failure:5

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    depends_on:
      - node-api
      - react-app
      - nginx
    restart: on-failure:5

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: on-failure:5

volumes:
  redis-data:
    driver: local
  node-data:
    driver: local
  nginx-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
