services:
  redis-cache:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  react-app:
    build: ./client
    ports:
      - "3000:80"

  node-api:
    build: ./server
    environment:
      SPOTIFY_CLIENT_ID: MY_CLIENT_ID
      SPOTIFY_CLIENT_SECRET: MY_CLIENT_SECRET
      COOKIE_SIGNER: MY_COOKIE_SIGNER
      JWT_SECRET: MY_JWT_SECRET
      TTL: 86400
    ports:
      - 3001:3001
    depends_on:
      - redis-cache

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - node-api
      - react-app

  post-start:
    image: redis/redis-stack-server:latest
    depends_on:
      - redis-cache
    command: ["sh", "-c", "redis-cli -h redis-cache CONFIG SET save '60 1'"]

volumes:
  redis-data:
    driver: local
