version: "3"
services:
  redis-stack-server:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server
    ports:
      - "6379:6379"
    restart: always
  sequence:
    image: sequence
    environment:
      SPOTIFY_CLIENT_ID: MY CLIENT ID
      SPOTIFY_CLIENT_SECRET: MY CLIENT SECRET
      COOKIE_SIGNER: MY COOKIE SIGNER
    ports:
      - 3001:3001
    depends_on:
      - redis-stack-server
