global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node-prometheus-exporter"
    static_configs:
      - targets: ["node-prometheus-exporter:9100"]

  - job_name: "nginx-react-exporter"
    static_configs:
      - targets: ["nginx-react-exporter:9113"]

  - job_name: "nginx-main-exporter"
    static_configs:
      - targets: ["nginx-main-exporter:9113"]
